PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "schema_migrations" ("version" varchar NOT NULL);
INSERT INTO "schema_migrations" VALUES('20151231083307');
INSERT INTO "schema_migrations" VALUES('20151231084925');
INSERT INTO "schema_migrations" VALUES('20160106050711');
CREATE TABLE "fake_dns_servers" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "target_server" varchar, "upstream" varchar, "trace_level" varchar, "hooking_hostnames" text, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "record_type" varchar, "loglevel" varchar);
INSERT INTO "fake_dns_servers" VALUES(1,'bluegreen-staging','bgstaging-971655135.ap-northeast-1.elb.amazonaws.com','8.8.8.8',NULL,'!barcelona.degica.com
!dashing.bgadmin.degica.com
!dash.bgadmin.degica.com
!grafana.bgadmin.degica.com
!consul.bgadmin.degica.com
!memails.degica.com
*.degica.com
www.acdsee.co.jp
jp.acdsee.com
acdsee.jp
www.corpusstore.jp
corpusstore.com
www.corpusstore.com
capture-soft.jp
remoteutilities.jp
rpgmakerweb.com
www.eboostr.jp
muvee.jp
movavi.jp
radio-tracker.jp
www.tune-bite.jp
tune-bite.jp
eboostr.com
easyweb3.com
clickteam.jp
www.mackeeper.co.jp
www.gdatastore.jp
www.jungle-fgwstore.jp
gameliner.jp
avg.co.jp
avgjapan.com
www.avgjapan.com
avgtaiwan.com
sayonaramail.com
www.sayonaramail.com
www.store.inksaver.jp
photomizer.jp
www.machdrive.jp
smartpctools.jp
ecoprintsaver.com
winrarjapan.com
windowblinds.jp
ask-ware.jp
ecoprint2.jp
www.ecoprint2.jp
eboostr.eu
www.free.avgtaiwan.com
returnil.jp
tegaki-ya.jp
avgfree.jp
www.avgfree.jp
www.nerostore.jp
shop.junglejapan.com
rpggameshq.com
www.rpggameshq.com
degigames.com
www.degigames.com
stickypassword.jp
excite-store.com
pandashop.jp
dreyestore.com
www.dreyestore.com
nerostore.com
www.kotoeu.com
sodapdf.jp
rpgmakerdc.com
support.panda.co.jp
spartan.jp
www.tkool.jp
railwaysims.com
shimapat.com
www.gamebox.tw
www.audials.jp
eboostr.jp
www.eboostr.com
www.gameliner.jp
www.rpgmakerweb.com
jp.rpgmakerweb.com
eshop.cyberfront.co.jp
store.junglejapan.com
jungle-fgwstore.jp
jp.xmind.net
www.avg.co.jp
free.avg.co.jp
www.muvee.jp
www.avgtaiwan.com
free.avgtaiwan.com
sayonaramail.com
store.inksaver.jp
www.capture-soft.jp
www.smartpctools.jp
www.ecoprintsaver.com
www.windowblinds.jp
www.winrarjapan.com
www.ask-ware.jp
www.returnil.jp
www.clickteam.jp
www.acdsee.jp
www.movavi.jp
www.pandashop.jp
panda.co.jp
www.panda.co.jp
panda.jp
www.panda.jp
www.rpg-tkool.com
kotoeu.com
www.rpg-tkool.com
kotoeu.com
fr.kotoeu.com
tkool.jp
tkool.jp
www.eboostr.eu
www.sodapdf.jp
gamebox.tw
www.railwaysims.com
audials.jp
www.stickypassword.jp
www.spartan.jp
store.lifeboat.jp
corpusstore.jp
store.freesoft-100.com
www.caveshmups.com
transition.tokyo
dariusburstcs.degica.com
','2016-01-03 01:08:55.989737','2016-03-07 07:10:44.574910','CNAME','INFO');
INSERT INTO "fake_dns_servers" VALUES(3,'passthrough','store.degica.com','8.8.8.8',NULL,'','2016-01-03 08:12:33.146254','2016-01-27 06:44:53.302954','CNAME','INFO');
INSERT INTO "fake_dns_servers" VALUES(4,'bluegreen-staged','bgstaged-1059858440.ap-northeast-1.elb.amazonaws.com','8.8.8.8',NULL,'!barcelona.degica.com
!dashing.bgadmin.degica.com
!dash.bgadmin.degica.com
!grafana.bgadmin.degica.com
!consul.bgadmin.degica.com
!memails.degica.com
*.degica.com
www.acdsee.co.jp
jp.acdsee.com
acdsee.jp
www.corpusstore.jp
corpusstore.com
www.corpusstore.com
capture-soft.jp
remoteutilities.jp
rpgmakerweb.com
www.eboostr.jp
muvee.jp
movavi.jp
radio-tracker.jp
www.tune-bite.jp
tune-bite.jp
eboostr.com
easyweb3.com
clickteam.jp
www.mackeeper.co.jp
www.gdatastore.jp
www.jungle-fgwstore.jp
gameliner.jp
avg.co.jp
avgjapan.com
www.avgjapan.com
avgtaiwan.com
sayonaramail.com
www.sayonaramail.com
www.store.inksaver.jp
photomizer.jp
www.machdrive.jp
smartpctools.jp
ecoprintsaver.com
winrarjapan.com
windowblinds.jp
ask-ware.jp
ecoprint2.jp
www.ecoprint2.jp
eboostr.eu
www.free.avgtaiwan.com
returnil.jp
tegaki-ya.jp
avgfree.jp
www.avgfree.jp
www.nerostore.jp
shop.junglejapan.com
rpggameshq.com
www.rpggameshq.com
degigames.com
www.degigames.com
stickypassword.jp
excite-store.com
pandashop.jp
dreyestore.com
www.dreyestore.com
nerostore.com
www.kotoeu.com
sodapdf.jp
rpgmakerdc.com
support.panda.co.jp
spartan.jp
www.tkool.jp
railwaysims.com
shimapat.com
www.gamebox.tw
www.audials.jp
eboostr.jp
www.eboostr.com
www.gameliner.jp
www.rpgmakerweb.com
jp.rpgmakerweb.com
eshop.cyberfront.co.jp
store.junglejapan.com
jungle-fgwstore.jp
jp.xmind.net
www.avg.co.jp
free.avg.co.jp
www.muvee.jp
www.avgtaiwan.com
free.avgtaiwan.com
sayonaramail.com
store.inksaver.jp
www.capture-soft.jp
www.smartpctools.jp
www.ecoprintsaver.com
www.windowblinds.jp
www.winrarjapan.com
www.ask-ware.jp
www.returnil.jp
www.clickteam.jp
www.acdsee.jp
www.movavi.jp
www.pandashop.jp
panda.co.jp
www.panda.co.jp
panda.jp
www.panda.jp
www.rpg-tkool.com
kotoeu.com
www.rpg-tkool.com
kotoeu.com
fr.kotoeu.com
tkool.jp
tkool.jp
www.eboostr.eu
www.sodapdf.jp
gamebox.tw
www.railwaysims.com
audials.jp
www.stickypassword.jp
www.spartan.jp
store.lifeboat.jp
corpusstore.jp
store.freesoft-100.com
www.caveshmups.com
transition.tokyo
dariusburstcs.degica.com
','2016-01-06 05:59:32.932253','2016-03-07 07:10:57.833167','CNAME','INFO');
INSERT INTO "fake_dns_servers" VALUES(5,'bgsecure-staging','bgs-haproxy-staged-601044019.ap-northeast-1.elb.amazonaws.com','8.8.8.8',NULL,'!barcelona.degica.com
!dashing.bgadmin.degica.com
!dash.bgadmin.degica.com
!grafana.bgadmin.degica.com
!consul.bgadmin.degica.com
!memails.degica.com
*.degica.com
www.acdsee.co.jp
jp.acdsee.com
acdsee.jp
www.corpusstore.jp
corpusstore.com
www.corpusstore.com
capture-soft.jp
remoteutilities.jp
rpgmakerweb.com
www.eboostr.jp
muvee.jp
movavi.jp
radio-tracker.jp
www.tune-bite.jp
tune-bite.jp
eboostr.com
easyweb3.com
clickteam.jp
www.mackeeper.co.jp
www.gdatastore.jp
www.jungle-fgwstore.jp
gameliner.jp
avg.co.jp
avgjapan.com
www.avgjapan.com
avgtaiwan.com
sayonaramail.com
www.sayonaramail.com
www.store.inksaver.jp
photomizer.jp
www.machdrive.jp
smartpctools.jp
ecoprintsaver.com
winrarjapan.com
windowblinds.jp
ask-ware.jp
ecoprint2.jp
www.ecoprint2.jp
eboostr.eu
www.free.avgtaiwan.com
returnil.jp
tegaki-ya.jp
avgfree.jp
www.avgfree.jp
www.nerostore.jp
shop.junglejapan.com
rpggameshq.com
www.rpggameshq.com
degigames.com
www.degigames.com
stickypassword.jp
excite-store.com
pandashop.jp
dreyestore.com
www.dreyestore.com
nerostore.com
www.kotoeu.com
sodapdf.jp
rpgmakerdc.com
support.panda.co.jp
spartan.jp
www.tkool.jp
railwaysims.com
shimapat.com
www.gamebox.tw
www.audials.jp
eboostr.jp
www.eboostr.com
www.gameliner.jp
www.rpgmakerweb.com
jp.rpgmakerweb.com
eshop.cyberfront.co.jp
store.junglejapan.com
jungle-fgwstore.jp
jp.xmind.net
www.avg.co.jp
free.avg.co.jp
www.muvee.jp
www.avgtaiwan.com
free.avgtaiwan.com
sayonaramail.com
store.inksaver.jp
www.capture-soft.jp
www.smartpctools.jp
www.ecoprintsaver.com
www.windowblinds.jp
www.winrarjapan.com
www.ask-ware.jp
www.returnil.jp
www.clickteam.jp
www.acdsee.jp
www.movavi.jp
www.pandashop.jp
panda.co.jp
www.panda.co.jp
panda.jp
www.panda.jp
www.rpg-tkool.com
kotoeu.com
www.rpg-tkool.com
kotoeu.com
fr.kotoeu.com
tkool.jp
tkool.jp
www.eboostr.eu
www.sodapdf.jp
gamebox.tw
www.railwaysims.com
audials.jp
www.stickypassword.jp
www.spartan.jp
store.lifeboat.jp
corpusstore.jp
store.freesoft-100.com
www.caveshmups.com
transition.tokyo
dariusburstcs.degica.com
','2016-01-26 01:56:16.672911','2016-06-14 01:29:13.490775','CNAME','WARN');
INSERT INTO "fake_dns_servers" VALUES(6,'bgsecure-live','bgp-haproxy-live-418435232.ap-northeast-1.elb.amazonaws.com','8.8.8.8',NULL,'!barcelona.degica.com
!dashing.bgadmin.degica.com
!dash.bgadmin.degica.com
!grafana.bgadmin.degica.com
!consul.bgadmin.degica.com
!memails.degica.com
*.degica.com
www.acdsee.co.jp
jp.acdsee.com
acdsee.jp
www.corpusstore.jp
corpusstore.com
www.corpusstore.com
capture-soft.jp
remoteutilities.jp
rpgmakerweb.com
www.eboostr.jp
muvee.jp
movavi.jp
radio-tracker.jp
www.tune-bite.jp
tune-bite.jp
eboostr.com
easyweb3.com
clickteam.jp
www.mackeeper.co.jp
www.gdatastore.jp
www.jungle-fgwstore.jp
gameliner.jp
avg.co.jp
avgjapan.com
www.avgjapan.com
avgtaiwan.com
sayonaramail.com
www.sayonaramail.com
www.store.inksaver.jp
photomizer.jp
www.machdrive.jp
smartpctools.jp
ecoprintsaver.com
winrarjapan.com
windowblinds.jp
ask-ware.jp
ecoprint2.jp
www.ecoprint2.jp
eboostr.eu
www.free.avgtaiwan.com
returnil.jp
tegaki-ya.jp
avgfree.jp
www.avgfree.jp
www.nerostore.jp
shop.junglejapan.com
rpggameshq.com
www.rpggameshq.com
degigames.com
www.degigames.com
stickypassword.jp
excite-store.com
pandashop.jp
dreyestore.com
www.dreyestore.com
nerostore.com
www.kotoeu.com
sodapdf.jp
rpgmakerdc.com
support.panda.co.jp
spartan.jp
www.tkool.jp
railwaysims.com
shimapat.com
www.gamebox.tw
www.audials.jp
eboostr.jp
www.eboostr.com
www.gameliner.jp
www.rpgmakerweb.com
jp.rpgmakerweb.com
eshop.cyberfront.co.jp
store.junglejapan.com
jungle-fgwstore.jp
jp.xmind.net
www.avg.co.jp
free.avg.co.jp
www.muvee.jp
www.avgtaiwan.com
free.avgtaiwan.com
sayonaramail.com
store.inksaver.jp
www.capture-soft.jp
www.smartpctools.jp
www.ecoprintsaver.com
www.windowblinds.jp
www.winrarjapan.com
www.ask-ware.jp
www.returnil.jp
www.clickteam.jp
www.acdsee.jp
www.movavi.jp
www.pandashop.jp
panda.co.jp
www.panda.co.jp
panda.jp
www.panda.jp
www.rpg-tkool.com
kotoeu.com
www.rpg-tkool.com
kotoeu.com
fr.kotoeu.com
tkool.jp
tkool.jp
www.eboostr.eu
www.sodapdf.jp
gamebox.tw
www.railwaysims.com
audials.jp
www.stickypassword.jp
www.spartan.jp
store.lifeboat.jp
corpusstore.jp
store.freesoft-100.com
www.caveshmups.com
transition.tokyo
dariusburstcs.degica.com
','2016-01-27 08:32:44.916547','2016-06-14 01:28:32.698227','CNAME','INFO');
INSERT INTO "fake_dns_servers" VALUES(7,'bluegreen-live','bglive-155187544.ap-northeast-1.elb.amazonaws.com','8.8.8.8',NULL,'!barcelona.degica.com
!dashing.bgadmin.degica.com
!dash.bgadmin.degica.com
!grafana.bgadmin.degica.com
!consul.bgadmin.degica.com
!memails.degica.com
*.degica.com
www.acdsee.co.jp
jp.acdsee.com
acdsee.jp
www.corpusstore.jp
corpusstore.com
www.corpusstore.com
capture-soft.jp
remoteutilities.jp
rpgmakerweb.com
www.eboostr.jp
muvee.jp
movavi.jp
radio-tracker.jp
www.tune-bite.jp
tune-bite.jp
eboostr.com
easyweb3.com
clickteam.jp
www.mackeeper.co.jp
www.gdatastore.jp
www.jungle-fgwstore.jp
gameliner.jp
avg.co.jp
avgjapan.com
www.avgjapan.com
avgtaiwan.com
sayonaramail.com
www.sayonaramail.com
www.store.inksaver.jp
photomizer.jp
www.machdrive.jp
smartpctools.jp
ecoprintsaver.com
winrarjapan.com
windowblinds.jp
ask-ware.jp
ecoprint2.jp
www.ecoprint2.jp
eboostr.eu
www.free.avgtaiwan.com
returnil.jp
tegaki-ya.jp
avgfree.jp
www.avgfree.jp
www.nerostore.jp
shop.junglejapan.com
rpggameshq.com
www.rpggameshq.com
degigames.com
www.degigames.com
stickypassword.jp
excite-store.com
pandashop.jp
dreyestore.com
www.dreyestore.com
nerostore.com
www.kotoeu.com
sodapdf.jp
rpgmakerdc.com
support.panda.co.jp
spartan.jp
www.tkool.jp
railwaysims.com
shimapat.com
www.gamebox.tw
www.audials.jp
eboostr.jp
www.eboostr.com
www.gameliner.jp
www.rpgmakerweb.com
jp.rpgmakerweb.com
eshop.cyberfront.co.jp
store.junglejapan.com
jungle-fgwstore.jp
jp.xmind.net
www.avg.co.jp
free.avg.co.jp
www.muvee.jp
www.avgtaiwan.com
free.avgtaiwan.com
sayonaramail.com
store.inksaver.jp
www.capture-soft.jp
www.smartpctools.jp
www.ecoprintsaver.com
www.windowblinds.jp
www.winrarjapan.com
www.ask-ware.jp
www.returnil.jp
www.clickteam.jp
www.acdsee.jp
www.movavi.jp
www.pandashop.jp
panda.co.jp
www.panda.co.jp
panda.jp
www.panda.jp
www.rpg-tkool.com
kotoeu.com
www.rpg-tkool.com
kotoeu.com
fr.kotoeu.com
tkool.jp
tkool.jp
www.eboostr.eu
www.sodapdf.jp
gamebox.tw
www.railwaysims.com
audials.jp
www.stickypassword.jp
www.spartan.jp
store.lifeboat.jp
corpusstore.jp
store.freesoft-100.com
www.caveshmups.com
transition.tokyo
dariusburstcs.degica.com
','2016-01-27 08:35:13.632315','2016-03-07 07:14:29.431075','CNAME','WARN');
INSERT INTO "fake_dns_servers" VALUES(8,'bgsecure-staged','bgp-haproxy-staged-796326353.ap-northeast-1.elb.amazonaws.com','8.8.8.8',NULL,'!barcelona.degica.com
!dashing.bgadmin.degica.com
!dash.bgadmin.degica.com
!grafana.bgadmin.degica.com
!consul.bgadmin.degica.com
!memails.degica.com
*.degica.com
www.acdsee.co.jp
jp.acdsee.com
acdsee.jp
www.corpusstore.jp
corpusstore.com
www.corpusstore.com
capture-soft.jp
remoteutilities.jp
rpgmakerweb.com
www.eboostr.jp
muvee.jp
movavi.jp
radio-tracker.jp
www.tune-bite.jp
tune-bite.jp
eboostr.com
easyweb3.com
clickteam.jp
www.mackeeper.co.jp
www.gdatastore.jp
www.jungle-fgwstore.jp
gameliner.jp
avg.co.jp
avgjapan.com
www.avgjapan.com
avgtaiwan.com
sayonaramail.com
www.sayonaramail.com
www.store.inksaver.jp
photomizer.jp
www.machdrive.jp
smartpctools.jp
ecoprintsaver.com
winrarjapan.com
windowblinds.jp
ask-ware.jp
ecoprint2.jp
www.ecoprint2.jp
eboostr.eu
www.free.avgtaiwan.com
returnil.jp
tegaki-ya.jp
avgfree.jp
www.avgfree.jp
www.nerostore.jp
shop.junglejapan.com
rpggameshq.com
www.rpggameshq.com
degigames.com
www.degigames.com
stickypassword.jp
excite-store.com
pandashop.jp
dreyestore.com
www.dreyestore.com
nerostore.com
www.kotoeu.com
sodapdf.jp
rpgmakerdc.com
support.panda.co.jp
spartan.jp
www.tkool.jp
railwaysims.com
shimapat.com
www.gamebox.tw
www.audials.jp
eboostr.jp
www.eboostr.com
www.gameliner.jp
www.rpgmakerweb.com
jp.rpgmakerweb.com
eshop.cyberfront.co.jp
store.junglejapan.com
jungle-fgwstore.jp
jp.xmind.net
www.avg.co.jp
free.avg.co.jp
www.muvee.jp
www.avgtaiwan.com
free.avgtaiwan.com
sayonaramail.com
store.inksaver.jp
www.capture-soft.jp
www.smartpctools.jp
www.ecoprintsaver.com
www.windowblinds.jp
www.winrarjapan.com
www.ask-ware.jp
www.returnil.jp
www.clickteam.jp
www.acdsee.jp
www.movavi.jp
www.pandashop.jp
panda.co.jp
www.panda.co.jp
panda.jp
www.panda.jp
www.rpg-tkool.com
kotoeu.com
www.rpg-tkool.com
kotoeu.com
fr.kotoeu.com
tkool.jp
tkool.jp
www.eboostr.eu
www.sodapdf.jp
gamebox.tw
www.railwaysims.com
audials.jp
www.stickypassword.jp
www.spartan.jp
store.lifeboat.jp
corpusstore.jp
store.freesoft-100.com
www.caveshmups.com
transition.tokyo
dariusburstcs.degica.com
','2016-05-09 07:18:07.192094','2016-06-14 01:28:54.096552','CNAME','INFO');
CREATE TABLE "log_messages" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "fake_dns_server_id" integer, "level" integer, "message" text, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "ar_internal_metadata" ("key" varchar PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
INSERT INTO "ar_internal_metadata" VALUES('environment','production','2016-03-03 09:15:55.395543','2016-03-03 09:15:55.395543');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('fake_dns_servers',8);
INSERT INTO "sqlite_sequence" VALUES('log_messages',7325);
CREATE UNIQUE INDEX "unique_schema_migrations" ON "schema_migrations" ("version");
COMMIT;
